### ISSUE TITLE
Migrar Figma a Blazor

### ISSUE THREAD

**Issue by Germandf** [Germandf/Juegardos.com#1]
- [x] Design System (colores y textos) @Germandf 
- [x] Inputs @Germandf 
- [x] Buttons @gabrielballone 
- [x] Icons @gabrielballone 
- Layout
  - [x] NavMenu @Germandf 
  - [x] Footer @gabrielballone 
  - [x] Modal @Germandf 
  - [x] Pagination @Germandf 
  - [x] Loading @Germandf 
- Games
  - [x] GamePlayBox @gabrielballone 
  - [x] OutstandingGameCard @gabrielballone 
  - [x] GameCard @Germandf 
  - [x] CarouselMultiple @Germandf 
- [x] Ads @Germandf

**Comment by Germandf** [comment]
Para los íconos, inicialmente probé con los oficiales de Iconify, pero te hacen importar un script en vez de un css y lo que hace es reemplazar el elemento por el ícono.

Si usábamos una cláusula @onclick con Blazor sobre ese elemento html, se perdía, por lo que no me pareció potable.

De momento, después lo discutimos, estoy usando los íconos de Material. 

https://materializecss.com/icons.html

El import ya lo hice en index.html, para usarlo en el link te muestra cómo, es muy fácil. Los componentes InputSearch.razor y NavMenu.razor ya están haciendo uso de esto, por si querés verlo de ejemplo.

**Comment by gabrielballone** [comment]
Recién hice commit con tres botones y el footer. Fue poquito pero me llevo tiempo  jaja. Más que nada el CSS, estoy re oxidado. Incluso el botón de Más Info me quedó mal porque no tuve tiempo de ver qué propiedad me falta arreglar. Tengo que repasar flex. 😢 
Vi tu commit del menú y el logo creo que completaste 👍🏻
Mañana seguimos! 🚀
