### ISSUE TITLE
Implementar páginas/comportamientos esenciales

### ISSUE THREAD

**Issue by Germandf** [Germandf/Juegardos.com#5]
### ¡¡Una vez que terminemos #1!!

- [x] Home
- [x] Search
- [x] Gameplay
- [x] My account
- [x] Game Modal
- [x] Sign In Modal
- [x] Sign Up Modal
- [x] Reset Password Modal

**Comment by Germandf** [comment]
@gabrielballone gabi sigo con la página de Search y todos los modals. Querés ir con la página mi cuenta que habías dicho y también terminar la página de gameplay? esta última es la más jodida de todas creo, cualquier cosa la vemos juntos después. Priorizá si querés que la pag mi cuenta quede terminada

**Comment by Germandf** [comment]
Dejé andando esto medio rápido, resolví el tema de transformar el nombre del juego a formato url y volverlo a formato no url, fixeé comportamiento del modal y el megamenu de que no se cerraba al clickear afuera, oculto la barra de búsqueda del navmenu según la página en la que está parado e hice una primera versión de la página de búsqueda (seteo por defecto lo que buscó de antemano en el input)

Mañana lo sigo, le falta responsive y varias cosas más 👋🏼 

![Recording 2022-05-29 at 23 28 05](https://user-images.githubusercontent.com/69018178/170906266-6c0ebe5b-30a2-43e8-89f8-6f2425019ad9.gif)

**Comment by gabrielballone** [comment]
Ayer completé página de cuenta de usuario. Hice el servicio para traer los datos de usuario pero no me quedó funcionando. Compila pero no me los levanta. Lo pushie anoche, debe ser algún detalle que se me escapó. Seguí el formato de clases e interfaces con los datos hardcodeados pero no funca.

**Comment by Germandf** [comment]
Dale, después nos juntamos y lo arreglamos rápido, de paso vemos una cosita que comenté en #10.

Hoy tenemos que dedicar el día a arreglar el layout de la página Gameplay y a implementar animaciones!!!! tenemos sólo hoy para esto último y es esencial para aprobar.

**Comment by gabrielballone** [comment]
Dale Ger, no creas que no me preocupa. Me siento un poco inutil porque soy lento para todo. Me falta práctica. Quisiera poder aportar mucho más
